import { H2, H3, P, Lead, Callout, PlainEnglish, Takeaways, CircuitDiagram, Code, M, Eq } from '../toolkit';

export default function QuantumWalks() {
  return (
    <>
      <Lead>
        A drunkard stumbling home takes a classical random walk — after <M>{'t'}</M> steps he's typically only{' '}
        <M>{'\\sqrt{t}'}</M> away from where he started. A quantum walker spreads <em>linearly</em>, reaching{' '}
        distance <M>{'t'}</M>, because its possible paths interfere. That difference powers some of the fastest
        known quantum algorithms.
      </Lead>

      <H2>Classical random walks, briefly</H2>
      <P>
        At each tick, flip a coin: heads, step right; tails, step left. Do this many times and your position
        follows a bell curve centered on the start, with spread growing like <M>{'\\sqrt{t}'}</M>. Random walks
        underpin everything from diffusion to Google's PageRank to Monte-Carlo simulation.
      </P>

      <H2>Going quantum: a coin in superposition</H2>
      <P>
        A <strong>quantum walk</strong> keeps the coin-and-step idea but makes the coin a qubit. Each step has
        two parts:
      </P>
      <P>
        <strong>The coin flip</strong> is a Hadamard on the coin qubit — putting it in superposition of “left”
        and “right.” <strong>The shift</strong> is a conditional move: increment the position if the coin says
        right, decrement if it says left. Because the coin is superposed, the walker moves both ways at once,
        and its many paths <em>interfere</em>.
      </P>
      <CircuitDiagram
        qubits={['coin', 'pos₀', 'pos₁', 'pos₂']}
        cols={[
          { boxes: [{ wire: 0, label: 'H' }], tag: 'coin' },
          { ctrl: { controls: [0], target: 1, kind: 'box', label: '±1', family: 'rot' }, tag: 'shift' },
          { boxes: [{ wire: 0, label: 'H' }], tag: 'coin' },
          { ctrl: { controls: [0], target: 1, kind: 'box', label: '±1', family: 'rot' }, tag: 'shift' },
          { measure: [1, 2, 3] },
        ]}
        caption="A coined quantum walk: alternate a Hadamard coin flip with a coin-conditioned ±1 shift on the position register."
      />

      <PlainEnglish>
        A classical walker forgets which way it came — every step is a fresh coin toss, so it dithers around
        home. A quantum walker keeps <em>all</em> its paths alive as amplitudes. Paths that double back tend to
        cancel; paths that press onward reinforce. The result is a walker that strides outward instead of
        shuffling in place.
      </PlainEnglish>

      <H2>The signature: ballistic, lopsided spreading</H2>
      <P>
        Plot a quantum walk's probability distribution and it looks nothing like a bell curve. Interference
        pushes probability out to the edges, producing two horns racing away from the origin at constant speed.
        The spread is <strong>ballistic</strong> (<M>{'\\sim t'}</M>) rather than diffusive (<M>{'\\sim\\sqrt{t}'}</M>) —
        a quadratic gain in how fast the walker explores.
      </P>
      <Eq>{'\\sigma_{\\text{classical}} \\sim \\sqrt{t} \\qquad\\text{vs}\\qquad \\sigma_{\\text{quantum}} \\sim t'}</Eq>
      <Callout kind="key" title="Why algorithm designers care">
        Faster spreading means faster exploration of a graph. Quantum walks give provable speedups for spatial
        search, element distinctness, and evaluating boolean formulas, and they are a fully{' '}
        <strong>universal</strong> model of quantum computation — anything a circuit can do, a suitably designed
        quantum walk can do too.
      </Callout>

      <H2>Running it in CasimirQ</H2>
      <P>
        CasimirQ's <strong>Quantum Walk</strong> algorithm builds this coined walk on a cyclic position register
        (the shift wraps around, using a modular increment). You choose the number of steps and whether the coin
        is symmetric, and it returns the resulting position distribution — the two-horned quantum signature laid
        out as data.
      </P>
      <Code
        lang="rust"
        title="quantum walk via casq-sdk"
        code={`// A coined quantum walk: 3 position qubits, 6 steps, symmetric coin.
let walk = client
    .algorithms()
    .quantum_walk(/* position_qubits */ 3, /* steps */ 6, /* symmetric */ true)
    .await?;

for point in &walk.distribution {
    println!("position {:>2}: p = {:.3}", point.position, point.probability);
}
// Notice the probability piling up at the extremes, not the center.`}
      />

      <H3>Discrete vs continuous</H3>
      <P>
        The coined walk above is a <em>discrete-time</em> quantum walk. There's also a{' '}
        <em>continuous-time</em> version, where the walk is generated by a graph's adjacency matrix acting as a
        Hamiltonian — a direct bridge to the next chapter on Hamiltonian simulation. Both share the same
        interference-driven speedup.
      </P>

      <Takeaways
        items={[
          <>A <strong>quantum walk</strong> replaces the random coin with a superposed qubit, so paths interfere.</>,
          <>Each step is a <strong>Hadamard coin</strong> plus a <strong>coin-conditioned ±1 shift</strong>.</>,
          <>Spreading is <strong>ballistic</strong> (<M>{'\\sim t'}</M>) vs classical diffusive (<M>{'\\sim\\sqrt t'}</M>) — a quadratic exploration speedup.</>,
          <>Quantum walks power spatial search and element distinctness, and are a <strong>universal</strong> model of computation.</>,
        ]}
      />
    </>
  );
}
